name: cocktail-cortical
channels:
  - conda-forge
dependencies:
  - python=3.10
  - eelbrain=0.41.2
  - mne
  - mne-bids
  - seaborn
  - numpy
  - scipy
  - pip
  - pip:
      # trftools isn't published on PyPI or conda-forge, only on GitHub.
      - git+https://github.com/christianbrodbeck/TRF-Tools.git
